Regtest v2 deployed + pool token naming convention
alexgo-io/alex-v1 pull request #150
Opened 2021-09-06 16:30 UTC by hyossid

2021-09-06 17:54 UTC, JBotwina approved these changes
Looking good. Since we are directly changing the contracts on main, our dev branch needs to catch up. I fear that main and dev have diverged too far at the moment and we should work hard to sync them this week.

2021-09-07 03:11 UTC, fiftyeightandeight requested changes
Please review my comments and make the appropriate changes. Thank you.

2021-09-07 03:11 UTC, fiftyeightandeight commented on clarity/contracts/pool-token-yield-usda-59760-usda.clar
> +(define-fungible-token ayusda-usda)
the name of the fungible-token does not include all the relevant information (i.e. expiry of yield token and token)

2021-09-07 03:11 UTC, fiftyeightandeight commented on clarity/contracts/pool-token-yield-usda-59760-usda.clar
> +  (ok "ayUSDA USDA LP Token")
See above

2021-09-07 03:11 UTC, fiftyeightandeight commented on clarity/contracts/pool-token-yield-usda-59760-usda.clar
> +  (ok "AYUSDAUSDA")
See above

2021-09-07 03:11 UTC, fiftyeightandeight commented on clarity/contracts/multisig-yield-usda-wbtc.clar
>    )
contract name should include all the relevant information, including expiry.

2021-09-07 13:30 UTC, hyossid commented
All fixed, please review again @fiftyeightandeight

2021-09-07 16:52 UTC, merged