Feat/buf uint conversion
alexgo-io/alex-v1 pull request #366
Opened 2021-11-25 08:52 UTC by SaadTahirTintash

2021-11-26 09:26 UTC, fiftyeightandeight requested changes

2021-11-26 09:26 UTC, fiftyeightandeight commented on clarity/contracts/flash-loan-user-margin-usda-wbtc.clar
> +            (memo-uint (buff-to-uint (unwrap-panic memo)))
Instead of `unwrap-panic`, please handle and throw a more informative error if `memo` is `none`.

2021-11-26 09:26 UTC, fiftyeightandeight commented on clarity/contracts/flash-loan-user-margin-wbtc-usda.clar
> +            (memo-uint (buff-to-uint (unwrap-panic memo)))
same as above

2021-11-26 11:13 UTC, naila24 commented
New error code added in case memo is none.

**ERROR** ERR-EXPIRY-IS-NONE 
**CODE** 2027
**DESCRIPTION** None passed in expiry

2021-11-28 07:28 UTC, fiftyeightandeight commented
> New error code added in case memo is none.
> 
> **ERROR** ERR-EXPIRY-IS-NONE **CODE** 2027 **DESCRIPTION** None passed in expiry

I see the changes are yet not implemented?

2021-11-29 07:24 UTC, SaadTahirTintash commented
> > New error code added in case memo is none.
> > **ERROR** ERR-EXPIRY-IS-NONE **CODE** 2027 **DESCRIPTION** None passed in expiry
> 
> I see the changes are yet not implemented?

I've updated it right now.

2021-11-29 10:35 UTC, fiftyeightandeight approved these changes

2021-11-29 10:36 UTC, merged